terms:
  - "100g Knusperkeks"
  - "100g Waffel"
  - "100g Marzipan"
  - "Mini Knusperkeks"
  - "Schokowürfel"
aliases:
  "SW": "Schokowürfel"
  "Mini KK": "Mini Knusperkeks"
  "Mini-Knusperkeks": "Mini Knusperkeks"
